name: Publish Package to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Project Dependencies
        run: |
          npm cache clean
          rm -f package-lock.json
          npm install

      - name: Publish Package to npm Registry
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CYPH_TOKEN }}
